import type { Metadata } from "next";
import "./globals.css";
import AppKitProvider from "@/context/wagmiContext";
import { Bounce, ToastContainer } from "react-toastify";
import NextTopLoader from "nextjs-toploader";
import "react-toastify/dist/ReactToastify.css";
import "@rainbow-me/rainbowkit/styles.css";
import MobileIndicator from "@/components/shared/MobileIndicator";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-primary-100 relative">
        <NextTopLoader color="#fff" showSpinner={false} />
        <ToastContainer
          position="top-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
          transition={Bounce}
        />
        <AppKitProvider>
          <div className="w-full h-full hidden lg:block">{children}</div>
          <div className="block lg:hidden h-full w-full">
            <MobileIndicator />
          </div>
        </AppKitProvider>
      </body>
    </html>
  );
}
